# Define All values of variable
# Consider Deployment chart
replicaCount: 3
app: nginx-app-03
name: nginx-app-03
image:
  repository: somnathmore/custom-nginx:v3
  pullPolicy: Always

  computeres:
    limits:
     cpu: "0.5"
     memory: 3Gi
    requests:
     cpu: "0.5"
     memory: 3Gi

ingress:
  className: nginx
  host: custom-nginx.codemaya.in
  
serviceType: ClusterIP
secretName: dockerhub
