# Define All values of variable
# Consider Staging chart
replicaCount: 2
app: nginx-app-03
name: nginx-app-03
image:
  repository: somnathmore/custom-nginx:v3
  pullPolicy: Never

  computeres:
    limits:
     cpu: "0.5"
     memory: 2Gi
    requests:
     cpu: "0.5"
     memory: 2Gi

ingress:
  className: nginx
  host: custom-nginx.codemaya.in

serviceType: ClusterIP


imagePullSecrets:
  - my-docker-secret
