apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}-service
spec:
  type: {{ .Values.serviceType }}
  ports:
    - port: 80
      targetPort: 80
  selector:
{{- include "nginx-app-label" . | nindent 4 }}
